### PR TITLE
Reverse string

### PR DESCRIPTION
**Pull request by s4shantanu**
This is my first time in hacktoberfest 2022, please approve my pull request.
Code is perfectly working i submitted on leetcode solution 
link - https://github.com/s4shantanu

### CODE REVIEW

**Review by s4shantanu — COMMENTED** [review]
This is my first contribution please approve my pull request.

**Comment by Atharva-D** [comment]
I would like to contribute to this issue. Please assign this to me @sanyamjain036

**Review by s4shantanu — COMMENTED** [review]
Please approve my PR. 
The code is working properly.

**Review by s4shantanu — COMMENTED** [review]
All files working properly code is running and maintained.

**Comment by s4shantanu** [comment]
Hey, I commit 78 files with top leetcode problems with a java solution.
Please approve my PR and merge them.

**Comment by s4shantanu** [comment]
> Hey, I commit 78 files with top leetcode problems with a java solution. Please approve my PR and merge them.

@sanyamjain036

**Pull request closed without merging**
